name: 1.20.1 Log to DC

on:
  workflow_dispatch:

jobs:
  send-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 1.20.1 branch
        uses: actions/checkout@v4
        with:
          ref: 1.20.1

      - name: Extract full changelog (skip first two lines)
        id: changelog
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          MODNAME="Aged"

          VERSION=$(grep -m1 '^# ' CHANGELOG.md | grep -oE '[0-9]+(\.[0-9]+)*')

          # Skip first two lines and save rest
          tail -n +3 CHANGELOG.md > changelog_full.txt

          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "modname=$MODNAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          MODNAME: ${{ steps.changelog.outputs.modname }}
          VERSION: ${{ steps.changelog.outputs.version }}
          BRANCH: ${{ steps.changelog.outputs.branch }}
        run: |
          CONTENT=$(cat changelog_full.txt)

          MESSAGE="$MODNAME $VERSION for Fabric $BRANCH has been released!\n"
          MESSAGE+="Changelog\n"
          MESSAGE+="$CONTENT\n"
          MESSAGE+="Downloads\n"
          MESSAGE+="https://example.com/download1\n"
          MESSAGE+="https://example.com/download2\n"
          MESSAGE+="Have a great time!"

          PAYLOAD=$(jq -nc --arg username "Changelog Bot" --arg content "$MESSAGE" \
            '{username: $username, content: $content}')

          echo "Payload to send:"
          echo "$PAYLOAD"

          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -H "Content-Type: application/json" \
            -X POST -d "$PAYLOAD" "$DISCORD_WEBHOOK_URL")

          echo "Discord webhook response status: $RESPONSE"

          if [ "$RESPONSE" != "204" ]; then
            echo "Failed to send message to Discord"
            exit 1
          fi
