name: 1.20.1 Log to DC

on:
  workflow_dispatch:

jobs:
  send-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 1.20.1 branch
        uses: actions/checkout@v4
        with:
          ref: 1.20.1

      - name: Extract changelog info (skip first two lines)
        id: changelog
        run: |
          BRANCH_NAME="1.20.1"
          MODNAME="Aged"

          VERSION=$(grep -m1 '^# ' CHANGELOG.md | grep -oE '[0-9]+(\.[0-9]+)*')

          tail -n +3 CHANGELOG.md > changelog_full.txt

          CONTENT=$(cat changelog_full.txt)

          echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "modname=$MODNAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT


      - name: Send Discord webhook embed
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: "${{ steps.changelog.outputs.modname }} ${{ steps.changelog.outputs.version }} for Fabric ${{ steps.changelog.outputs.branch }} has been released!"
          embed-description: |
            **Changelog**
            ```md
            ${{ steps.changelog.outputs.content }}
            ```
            **Downloads**
            <:modrinth:1401269188215046265> https://modrinth.com/modpack/aged/version/${{ steps.changelog.outputs.version }}
          embed-footer-text: "Have a great time!"
          embed-color: 0x00FF80
